controlaesadiacsa/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import include
from restapp.api.router import router_posts
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('panel.urls')),
    path('api/', include(router_posts.urls))
]

panel/urls.py
from django.contrib import admin
from django.urls import path

from . import views

urlpatterns = [
    path('test_favicon', views.home_view, name="homeFavicon"),
    path('', views.autenticacion, name="autenticacion"),
    path('signout', views.signout, name="signout"),
    path('home', views.index, name="index"),
    path('listar', views.listar, name="listar"),
    path('agregar', views.agregar, name="agregar"),
    path('actualizar', views.actualizar, name="actualizar"),
    path('eliminar', views.eliminar, name="eliminar"),
    path('livedata', views.livedata, name="livedata"),
    path('livedata/agregar', views.livedata_agregar, name="livedata_agregar"),
    path('livedata/eliminar', views.livedata_eliminar, name="livedata_eliminar"),
    path('marcacion', views.marcacion, name="marcacion"),
    path('noregistrados', views.noregistrados, name="noregistrados"),    
]

panel/models.py
from django.db import models

# Create your models here.

class PersonalRegistrado(models.Model):
    id = models.IntegerField(primary_key=True)
    cardid = models.IntegerField(null=False)
    nombre = models.CharField(max_length=50, null=False)
    apellido = models.CharField(max_length=50, null=False)
    cargo = models.CharField(max_length=50, null=True)
    correo = models.CharField(max_length=50, null=False)
    telefono = models.IntegerField(null=True)
    f_nac = models.DateField(null=True)
    f_registro = models.DateTimeField(auto_now_add=True, null=False)

    def __str__(self):
        return str(self.cardid)+" "+str(self.nombre)+" "+str(self.apellido)
    
    class Meta:
        db_table = 'PersonalRegistrado'

class LiveData(models.Model):
    id = models.IntegerField(primary_key=True)
    cardid = models.IntegerField(null=False)
    nombre = models.CharField(max_length=50, null=True)
    apellido = models.CharField(max_length=50, null=True)
    cargo = models.CharField(max_length=50, null=True)
    f_ingreso = models.DateField(null=True)
    h_ingreso = models.TimeField(null=True)

    class Meta:
        db_table = 'LiveData'

class Marcacion(models.Model):
    id = models.IntegerField(primary_key=True)
    cardid = models.IntegerField(null=False)
    nombre = models.CharField(max_length=50, null=True)
    apellido = models.CharField(max_length=50, null=True)
    cargo = models.CharField(max_length=50, null=True)
    f_evento = models.DateField(null=True)
    h_evento = models.TimeField(null=True)
    evento = models.CharField(max_length=50, null=True)

    class Meta:
        db_table = 'Marcacion'

class NoRegistrados(models.Model):
    id = models.IntegerField(primary_key=True)
    cardid = models.IntegerField(null=False)
    f_evento = models.DateField(null=True)
    h_evento = models.TimeField(null=True)
    evento = models.CharField(max_length=50, null=True)

    class Meta:
        db_table = 'NoRegistrados'

#######################

panel/views.py
from django.http.request import HttpRequest
from django.http.response import HttpResponse
from django.shortcuts import render, redirect

from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate

from . import models

#from datetime import datetime
from django.utils import timezone
from django.utils.timezone import activate
import pytz

# Create your views here.
TEMPLATE_DIRS = (
    'os.path.join(BASE_DIR, "templates")'
)

def home_view(request: HttpRequest) -> HttpResponse:
    return render(request, 'home.html')

def autenticacion(request):
    if request.method == 'GET':
        return render(request, "login.html",{
            'error': 'Username or password incorrect.'
        })
    
    user = authenticate(
        request, username=request.POST['username'], password=request.POST['password'])

    if user is None:
        return render(request, 'login.html', {
            'error': 'Username or password incorrect'
        })
    else:
        login(request, user)
        return redirect('index')    
    
@login_required(login_url = 'autenticacion')
def signout(request):
    logout(request)
    return redirect("autenticacion")

@login_required(login_url = 'autenticacion')
def index(request):
    users = models.LiveData.objects.all()
    data = {'total': users.count()}
    return render(request, "index.html", data)

@login_required(login_url = 'autenticacion')
def listar(request):
    users = models.PersonalRegistrado.objects.all()
    datos = { 'personalregistrado' : users}
    return render(request, "crud_aesadiacsa/listar.html", datos)

@login_required(login_url = 'autenticacion')
def agregar(request):
    if request.method == 'POST':
        print(request.POST.get('cardid'))
        print(request.POST.get('nombre'))
        print(request.POST.get('apellido'))
        print(request.POST.get('cargo'))
        print(request.POST.get('telefono'))
        print(request.POST.get('correo'))
        print(request.POST.get('f_nac'))
        #agregar datos
        if request.POST.get('cardid') and request.POST.get('nombre') and request.POST.get('apellido') and request.POST.get('telefono') and request.POST.get('correo') and request.POST.get('f_nac'):
            users = models.PersonalRegistrado.objects.all()
            cantidadactualRegistrada = users.count()
            user = models.PersonalRegistrado()
            user.id = cantidadactualRegistrada+1
            user.cardid = request.POST.get('cardid')
            user.nombre = request.POST.get('nombre')
            user.apellido = request.POST.get('apellido')
            user.cargo = request.POST.get('cargo')
            user.correo = request.POST.get('correo')
            user.telefono = request.POST.get('telefono')
            user.f_nac = request.POST.get('f_nac')
            user.f_registro = timezone.now()
            user.save()
            return redirect('listar')
        datos = { 'r2' : "Debe ingresar todos los campos correctamente"}
        return render(request, "crud_aesadiacsa/agregar.html", datos)

    else:
        return render(request, "crud_aesadiacsa/agregar.html")

@login_required(login_url = 'autenticacion')
def actualizar(request):
    if request.method == 'POST':
        print(request.POST.get('id'))
        print(request.POST.get('cardid'))
        print(request.POST.get('nombre'))
        print(request.POST.get('apellido'))
        print(request.POST.get('cargo'))
        print(request.POST.get('telefono'))
        print(request.POST.get('correo'))
        print(request.POST.get('f_nac'))
        #agregar datos
        if request.POST.get('cardid') and request.POST.get('id') and request.POST.get('nombre') and request.POST.get('apellido') and request.POST.get('telefono') and request.POST.get('correo') and request.POST.get('f_nac'):
            user = models.PersonalRegistrado()
            user.id = request.POST.get('id')
            user.cardid = request.POST.get('cardid')
            user.nombre = request.POST.get('nombre')
            user.apellido = request.POST.get('apellido')
            user.cargo = request.POST.get('cargo')
            user.correo = request.POST.get('correo')
            user.telefono = request.POST.get('telefono')
            user.f_nac = request.POST.get('f_nac')
            user.f_registro = timezone.now()
            user.save()
            return redirect('listar')
        datos = { 'r2' : "Debe ingresar todos los campos correctamente"}
        return render(request, "crud_aesadiacsa/actualizar.html", datos)    
    else:
        users = models.PersonalRegistrado.objects.all()
        datos = { 'personalregistrado' : users} 

        return render(request, "crud_aesadiacsa/actualizar.html", datos)

@login_required(login_url = 'autenticacion')
def eliminar(request):
    if request.method == 'POST':
        print(request.POST.get('id'))
        #agregar datos
        if request.POST.get('id'):
            id_a_borrar = request.POST.get('id')
            tupla = models.PersonalRegistrado.objects.get(id=id_a_borrar)
            tupla.delete()
            return redirect('listar')
        datos = { 'r2' : "Debe ingresar todos los campos correctamente"}
        return render(request, "crud_aesadiacsa/eliminar.html", datos) 
    else:    
        users = models.PersonalRegistrado.objects.all()
        datos = { 'personalregistrado' : users} 
        return render(request, "crud_aesadiacsa/eliminar.html", datos)

@login_required(login_url = 'autenticacion')
def livedata(request):
    users = models.LiveData.objects.all()
    #activate(pytz.timezone('America/Lima'))
    #print(timezone.now())
    datos = { 'livedata' : users,
             'fecha_y_hora': timezone.now(),}
    return render(request, "livedata/livedata.html", datos)

@login_required(login_url = 'autenticacion')
def livedata_agregar(request):
    if request.method == 'POST':
        print(request.POST.get('cardid'))
        print(request.POST.get('nombre'))
        print(request.POST.get('apellido'))
        print(request.POST.get('cargo'))
        print(request.POST.get('f_ingreso'))
        print(request.POST.get('h_ingreso'))
        #agregar datos
        if request.POST.get('cardid') and request.POST.get('nombre') and request.POST.get('apellido') and request.POST.get('cargo') and request.POST.get('f_ingreso') and request.POST.get('h_ingreso'):
            users = models.LiveData.objects.all()
            cantidadactualRegistrada = users.count()
            user = models.LiveData()
            user.id = cantidadactualRegistrada+1
            user.cardid = request.POST.get('cardid')
            user.nombre = request.POST.get('nombre')
            user.apellido = request.POST.get('apellido')
            user.cargo = request.POST.get('cargo')
            user.f_ingreso = request.POST.get('f_ingreso')
            user.h_ingreso = request.POST.get('h_ingreso')
            user.save()
            return redirect('livedata')
        datos = { 'r2' : "Debe ingresar todos los campos correctamente"}
        return render(request, "livedata/livedata_agregar.html", datos)

    else:
        return render(request, "livedata/livedata_agregar.html")

@login_required(login_url = 'autenticacion')
def livedata_eliminar(request):
    if request.method == 'POST':
        print(request.POST.get('id'))
        #agregar datos
        if request.POST.get('id'):
            id_a_borrar = request.POST.get('id')
            tupla = models.LiveData.objects.get(id=id_a_borrar)
            tupla.delete()
            return redirect('livedata')
        datos = { 'r2' : "Debe ingresar todos los campos correctamente"}
        return render(request, "livedata/livedata_eliminar.html", datos) 
    else:    
        users = models.LiveData.objects.all()
        datos = { 'livedata' : users} 
        return render(request, "livedata/livedata_eliminar.html", datos)

@login_required(login_url = 'autenticacion')
def marcacion(request):
    users = models.Marcacion.objects.all()
    datos = { 'marcacion' : users}
    return render(request, "marcacion/marcacion.html", datos)

@login_required(login_url = 'autenticacion')
def noregistrados(request):
    users = models.NoRegistrados.objects.all()
    datos = { 'noregistrados' : users}
    return render(request, "noregistrados/noregistrados.html", datos)

panel/templates/index.html
{% extends 'index_master.html' %}

{% block content %}

    <!-- page content -->
        <div class="right_col" role="main">
          <h1>Resumen del personal en mina</h1>
          <div class="row" style="display: inline-block;" >
            <div class="tile_count">
              <div class="col-md-12 col-sm-12  tile_stats_count">
                <span class="count_top"><i class="fa fa-user"></i> Total de personal en mina</span>
                <div class="count">{{total}}</div>
              </div>
            </div>
          </div>
        </div>
    <!-- /page content -->
{% endblock %}

panel/templates/index_master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'favicon.ico' %}">

    <title>AESA-DIACSA Control</title>

    <!-- Bootstrap -->
    <link href="{% static '/FrWork/admin_lte/vendors/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static '/FrWork/admin_lte/vendors/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static '/FrWork/admin_lte/vendors/nprogress/nprogress.css' %}" rel="stylesheet">
    <!-- iCheck -->
    <link href="{% static '/FrWork/admin_lte/vendors/iCheck/skins/flat/green.css' %}" rel="stylesheet">
	
    <!-- bootstrap-progressbar -->
    <link href="{% static '/FrWork/admin_lte/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css' %}" rel="stylesheet">
    <!-- JQVMap -->
    <link href="{% static '/FrWork/admin_lte/vendors/jqvmap/dist/jqvmap.min.css' %}" rel="stylesheet"/>
    <!-- bootstrap-daterangepicker -->
    <link href="{% static '/FrWork/admin_lte/vendors/bootstrap-daterangepicker/daterangepicker.css' %}" rel="stylesheet">

    <!-- bootstrap-switchery -->
    <link href="{% static '/FrWork/admin_lte/vendors/switchery/switchery.css' %}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{% static '/FrWork/admin_lte/build/css/custom.min.css' %}" rel="stylesheet">

    {% block head %}
    {% endblock %}
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="home" class="site_title"><i class="fa fa-connectdevelop"></i> <span>AESA -DIACSA Personal</span></a>
            </div>

            <div class="clearfix"></div>

            <br />

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <h3>General</h3>
                <ul class="nav side-menu">
                  <li><a href="/home"><i class="fa fa-home"></i> Resumen</a>
                  </li>
                  <li><a><i class="fa fa-users"></i> Usuarios <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="/listar"><i class="fa fa-user"></i> Listar</a></li>
                      {% if perms.panel.change_livedata %}
                        <li><a href="/agregar"><i class="fa fa-user-plus"></i> Agregar</a></li>
                        <li><a href="/actualizar"><i class="fa fa-edit"></i> Actualizar</a></li>
                        <li><a href="/eliminar"><i class="fa fa-user-times"></i> Eliminar</a></li>
                      {% endif %}
                    </ul>
                  </li>
                  <li><a href="/livedata"><i class="fa fa-clock-o"></i> Personal Tiempo Real</a>
                  </li>
                  <li><a href="/marcacion"><i class="fa fa-list-alt"></i> Historial</a>
                  </li>
                  <li><a href="/noregistrados"><i class="fa fa-user-secret"></i> Personal No Registrado</a>
                  </li>
                </ul>
              </div>
            </div>
            <!-- /sidebar menu -->

          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>
              <nav class="nav navbar-nav">
                <ul class="navbar-right">
                  <li class="nav-item dropdown open" style="padding-left: 15px;">
                    <a href="javascript:;" class="user-profile dropdown-toggle" aria-haspopup="true" id="navbarDropdown" data-toggle="dropdown" aria-expanded="false">
                      Usuario: {{user.username}}
                    </a>
                    <div class="dropdown-menu dropdown-usermenu pull-right" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item"  href="/signout"><i class="fa fa-sign-out pull-right"></i> Log Out</a>
                    </div>
                  </li>
                </ul>
              </nav>
          </div>
        </div>
        <!-- /top navigation -->



        <!-- ****************************************   -->

        {% block content %}
        {% endblock %}


        <!-- footer content -->
        <footer>
          <div class="pull-right">
            AESA MINERIA - Aplicación minera desarrollada por <a href="http://www.diacsa.com/">Diacsa</a>
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
      </div>
    </div>

    <!-- jQuery -->
    <script src="{% static '/FrWork/admin_lte/vendors/jquery/dist/jquery.min.js' %}"></script>
    <!-- Bootstrap -->
    <script src="{% static '/FrWork/admin_lte/vendors/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
    <!-- FastClick -->
    <script src="{% static '/FrWork/admin_lte/vendors/fastclick/lib/fastclick.js' %}"></script>
    <!-- NProgress -->
    <script src="{% static '/FrWork/admin_lte/vendors/nprogress/nprogress.js' %}"></script>
    <!-- Chart.js -->
    <script src="{% static '/FrWork/admin_lte/vendors/Chart.js/dist/Chart.min.js' %}"></script>
    <!-- gauge.js -->
    <script src="{% static '/FrWork/admin_lte/vendors/gauge.js/dist/gauge.min.js' %}"></script>
    <!-- bootstrap-progressbar -->
    <script src="{% static '/FrWork/admin_lte/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js' %}"></script>
    <!-- iCheck -->
    <script src="{% static '/FrWork/admin_lte/vendors/iCheck/icheck.min.js' %}"></script>
    <!-- Skycons -->
    <script src="{% static '/FrWork/admin_lte/vendors/skycons/skycons.js' %}"></script>
    <!-- Flot -->
    <script src="{% static '/FrWork/admin_lte/vendors/Flot/jquery.flot.js' %}"></script>
    <script src="{% static '/FrWork/admin_lte/vendors/Flot/jquery.flot.pie.js' %}"></script>
    <script src="{% static '/FrWork/admin_lte/vendors/Flot/jquery.flot.time.js' %}"></script>
    <script src="{% static '/FrWork/admin_lte/vendors/Flot/jquery.flot.stack.js' %}"></script>
    <script src="{% static '/FrWork/admin_lte/vendors/Flot/jquery.flot.resize.js' %}"></script>
    <!-- Flot plugins -->
    <script src="{% static '/FrWork/admin_lte/vendors/flot.orderbars/js/jquery.flot.orderBars.js' %}"></script>
    <script src="{% static '/FrWork/admin_lte/vendors/flot-spline/js/jquery.flot.spline.min.js' %}"></script>
    <script src="{% static '/FrWork/admin_lte/vendors/flot.curvedlines/curvedLines.js' %}"></script>
    <!-- DateJS -->
    <script src="{% static '/FrWork/admin_lte/vendors/DateJS/build/date.js' %}"></script>
    <!-- JQVMap -->
    <script src="{% static '/FrWork/admin_lte/vendors/jqvmap/dist/jquery.vmap.js' %}"></script>
    <script src="{% static '/FrWork/admin_lte/vendors/jqvmap/dist/maps/jquery.vmap.world.js' %}"></script>
    <script src="{% static '/FrWork/admin_lte/vendors/jqvmap/examples/js/jquery.vmap.sampledata.js' %}"></script>
    <!-- bootstrap-daterangepicker -->
    <script src="{% static '/FrWork/admin_lte/vendors/moment/min/moment.min.js' %}"></script>
    <script src="{% static '/FrWork/admin_lte/vendors/bootstrap-daterangepicker/daterangepicker.js' %}"></script>
    

    <!-- Custom Theme Scripts -->
    <script src="{% static '/FrWork/admin_lte/build/js/custom.min.js' %}"></script>
	 
    <!-- Custom Theme Scripts for tables -->
    <script src="{% static 'app.js' %}"></script>
    
    {% block scripts %}
    {% endblock %}

  </body>
</html>